# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[43,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/ArsenicAndLace/issues"
license="LGPL 3"
logoFile="logo.png"

[[mods]]
modId="arsenic"
version="${file.jarVersion}"
displayName="akkamaddi's Arsenic and Lace"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/ArsenicAndLace/1.19/update.json"
displayURL="http://minecraft.curseforge.com/projects/akkamaddis-arsenic-and-lace"
credits="Thanks to akkamaddi for creating the original mod (with help from AleXndrTheGr8st) and to Sinhika for porting and maintaining it. Credit for the Necrotic Furnace idea and texture belongs to akkamaddi."
authors="akkamaddi, Sinhika"
description='''Addition of Arsenic, Arsenide Bronze, Arsenide Gold and Tenebrium, as well as Lace Shrouds. Fusion Furnace and Simple Ores add-on.
'''

[[dependencies.arsenic]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.0,44.0.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.arsenic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1,19.3)"
    ordering="NONE"
    side="BOTH"

[[dependencies.arsenic]]
    modId="simplecorelib"
    mandatory=true
    versionRange="[1.19.2-5.1.0.1, 1.19.3)"
    ordering="NONE"
    side="BOTH"    

[[dependencies.arsenic]]
    modId="simpleores"
    mandatory=false
    versionRange="[1.19.2-5.1.0.0, 1.19.3)"
    ordering="BEFORE"
    side="BOTH"    

[[dependencies.arsenic]]
    modId="fusion"
    mandatory=true
    versionRange="[1.19.2-5.1.0.0, 1.19.3)"
    ordering="NONE"
    side="BOTH"
    
